vich_uploader:
    db_driver: orm

    mappings:
        curriculum:
            uri_prefix: /uploads/curriculums
            upload_destination: '%kernel.project_dir%/public/uploads/curriculums'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
        job_description:
            uri_prefix: /uploads/job_description
            upload_destination: '%kernel.project_dir%/public/uploads/job_description'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
